### ISSUE TITLE
Bug: installation error "could not rename downloaded file"

### ISSUE THREAD

**Issue by joelparkerhenderson** [willcrichton/flowistry#19] opened 2021-09-29 21:46 UTC
# Problem
When I try to install flowistry for the first time via the Code marketplace, on current Code and current macOS, then installation fails.

# Logs

**OS:** darwin (20.5.0)
**VSCode:** 1.60.2
**Error message**
```
info: syncing channel updates for 'nightly-2021-09-23-x86_64-apple-darwin'
info: latest update on 2021-09-23, rust version 1.57.0-nightly (308dffd25 2021-09-22)
info: downloading component 'cargo'
error: component download failed for cargo-x86_64-apple-darwin: could not rename downloaded file from '/Users/joel/.rustup/downloads/a8674a2e1c94fe147f0fb05303de67130dc6dfc9b33f2eb9a07194a5b85ee2ec.partial' to '/Users/joel/.rustup/downloads/a8674a2e1c94fe147f0fb05303de67130dc6dfc9b33f2eb9a07194a5b85ee2ec'
```

**Full log:** https://paste.rs/Uf1

**Comment by willcrichton** [comment] 2021-09-29 23:38
Thanks for the report @joelparkerhenderson. This seems to be the same issue as #13. I haven't found the bug yet since I can't reproduce it on my machine, but I'll keep investigating.

**Comment by willcrichton** [comment] 2021-09-30 16:15
See #13 -- closing this for now.

**Closed by willcrichton** 2021-09-30 16:15 UTC
Labels: bug, ui
