### ISSUE TITLE
Flowistry outputs nonsense on Windows

### ISSUE THREAD

**Issue by 1221long** [willcrichton/flowistry#27] opened 2021-11-05 01:32 UTC
# Problem
after I download and install successfully. VS gave me the error.

# Logs

**OS:** win32 (10.0.19043)
**VSCode:** 1.61.2
**Error message**
```
'D:\Program' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
```

**Full log:** https://paste.rs/P3z

**Comment by willcrichton** [comment] 2021-11-05 01:46
Oh my! That's quite the error.

I will note that Flowistry does not have first-class support for Windows yet. I tried it briefly on a VM and found a bunch of strange errors that don't show up in Linux or OSX. I will ping this issue though if I do get around to supporting Windows!

**Comment by zeramorphic** [comment] 2022-03-25 22:32
Hi @1221long, are you still having this issue? On current builds of the VS Code extension, I can't reproduce your problem.

**Comment by willcrichton** [comment] 2022-05-28 17:25
This should be fixed now.

**Closed by willcrichton** 2022-05-28 17:25 UTC
Labels: bug, platform-support
